apiVersion: v2
name: noob
description: Code judge platform on Kubernetes
type: application
home: https://github.com/kzh/noob
dependencies:
  - name: redis
    version: 10.7.11
    repository: https://charts.bitnami.com/bitnami
    alias: sessions
  - name: mongodb
    version: 8.2.1
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 7.5.6
    repository: https://charts.bitnami.com/bitnami
version: 0.1.0
appVersion: 0.1.0
