mongodb:
  auth:
    rootPassword: "MONGODB_TEMP"

postgresql:
  postgresqlPassword: "POSTGRESQL_TEMP"

sessions:
  password: "SESSIONS_TEMP"
  cluster:
    enabled: false

rabbitmq:
  auth:
    password: "RABBITMQ_TEMP"
    erlangCookie: "ERLANG_COOKIE"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
