nginx-ingress:
    controller:
        hostNetwork: true
        service:
            type: NodePort
        defaultBackendService: "noob/noob-frontend"
    rbac:
        create: true
    defaultBackend:
        enabled: false
mongodb:
    mongodbRootPassword: "MONGODB_TEMP"
redis:
    cluster:
        enabled: false
    password: "REDIS_TEMP"
rabbitmq:
    livenessProbe:
        enabled: false
    readinessProbe:
        enabled: false
    rabbitmq:
        password: "RABBITMQ_TEMP"
