nginx-ingress:
    controller:
        hostNetwork: true
        service:
            type: NodePort
        defaultBackendService: "noob/noob-frontend"
    rbac:
        create: true
    defaultBackend:
        enabled: false
