version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    container_name: uhkevin/noob-auth
    image: uhkevin/noob-auth
    ports:
    - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: ./cmd/frontend/Dockerfile
    container_name: uhkevin/noob-frontend
    image: uhkevin/noob-frontend
    ports:
    - "8080:8080"
  problems:
    build:
      context: .
      dockerfile: ./cmd/problems/Dockerfile
    container_name: uhkevin/noob-problems
    image: uhkevin/noob-problems
    ports:
    - "8080:8080"
  submissions:
    build:
      context: .
      dockerfile: ./cmd/submissions/Dockerfile
    container_name: uhkevin/noob-submissions
    image: uhkevin/noob-submissions
    ports:
    - "8080:8080"
  executor:
    build:
      context: .
      dockerfile: ./cmd/executor/Dockerfile
    container_name: uhkevin/noob-executor
    image: uhkevin/noob-executor
