version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: uhkevin/noob-auth
    image: uhkevin/noob-auth
    ports:
    - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: uhkevin/noob-frontend
    image: uhkevin/noob-frontend
    ports:
    - "8080:8080"
  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    container_name: uhkevin/noob-admin
    image: uhkevin/noob-admin
    ports:
    - "8080:8080"
  scheduler:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    container_name: uhkevin/noob-scheduler
    image: uhkevin/noob-scheduler
    ports:
    - "8080:8080"
