apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dockerd
  labels:
    app: {{ .Release.Name }}-dockerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dockerd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dockerd
    spec:
      containers:
      - name: {{ .Release.Name }}-dockerd
        image: docker:18.06-dind
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dockerd
spec:
  selector:
    app: {{ .Release.Name }}-dockerd
  ports:
  - protocol: TCP
    port: 2375
    targetPort: 2375
