apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-executor
  labels:
    app: {{ .Release.Name }}-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-executor
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-executor
    spec:
      containers:
      - name: {{ .Release.Name }}-executor
        image: uhkevin/noob-executor
        env:
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: noob-rabbitmq
                key: rabbitmq-password
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: noob-mongodb
                key: mongodb-root-password
          - name: DOCKER_HOST
            value: "tcp://localhost:2375"
          - name: DOCKER_API_VERSION
            value: "1.38"
      - name: {{ .Release.Name }}-dockerd
        image: docker:18.06-dind
        securityContext:
          privileged: true
